### ISSUE TITLE
Kind request to remove package from Atmosphere

### ISSUE THREAD

**Issue by dandv** [waitingkuo/meteor-nvd3#3]
We now have an [official](https://github.com/MeteorPackaging/discussions/issues/2) integration at https://atmospherejs.com/nvd3/nvd3

Please run this command to deprecate your package:

    meteor admin set-unmigrated <package-name>

To remove `mrt` as a contributor:

    meteor admin maintainers <your_username>:<your_package> --remove mrt

If you were originally the maintainer on the old package system, you can attach your Meteor Developer account at http://atmosphere.meteor.com/accounts, then ping **tmeasday** to give you ownership of the old package.

**Comment by waitingkuo** [comment]
done! is it removed now?

**Comment by dandv** [comment]
Thanks, let's see - what was the Atmosphere URL of your package?

**Comment by waitingkuo** [comment]
I can't find it now

**Comment by dandv** [comment]
Removal is successful if the package no longer appears at https://atmospherejs.com/?q=nvd3

**Comment by dandv** [comment]
Apparently it's still there, mrt:nvd3-revised. Did you attach your Meteor Developer account at http://atmosphere.meteor.com/accounts?

**Comment by waitingkuo** [comment]
I've attached that. Is mrt:nvd3-revised mine?

**Comment by dandv** [comment]
I think so. Pinging @tmeasday.

**Comment by tmeasday** [comment]
Hey! That package is owned by `bandini84`, who hasn't yet had a MD account linked. Perhaps you did the wrong atmosphere user @waitingkuo?
